name: PHP Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  phpunit:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
        operating-system:
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"

      - name: PHP info
        run: |
          php -v
          php -m

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Run the test
        run: vendor/bin/phpunit FooTest.php
